### ISSUE TITLE
cindex equal 0

### ISSUE THREAD

**Issue by tcoroller** [Novartis/torchsurv#61]
File "/home/corolth1/torchsurv/src/torchsurv/metrics/cindex.py", line 568, in _p_value_noether
    raise ValueError(
ValueError: The standard error of concordance index must be a positive value.

**Comment by melodiemonod** [comment]
Hi @tcoroller , 

I don't think the edits proposed are correct because it would lead to a division by 0 (https://github.com/Novartis/torchsurv/blob/57845ede441df4c20ea9dba3cd6c75f09376e981/src/torchsurv/metrics/cindex.py#L590). 

The se should not be 0. Do you want to give me a reproducible code so I can check the error you got?

**Comment by tcoroller** [comment]
Sounds good, let me try to do a reproducible example

**Comment by tcoroller** [comment]
Unless we can do something like:
` (self.cindex - null_value) / (cindex_se  + eps)` ?

**Comment by melodiemonod** [comment]
I mean intuitively the c-index standard error should never be 0. I'm curious to know what can can lead to this!
